@baseUrl = http://localhost:3333
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlYTFmMWRiOS02OGI1LTRjYjUtOTUzMi1kY2JiOTRmNDhiMWEiLCJpYXQiOjE3MTQwOTgyNDYsImV4cCI6MTcxNDcwMzA0Nn0.jq6P5tsbU5ZMafAsMCLrF8kpc3ZvJg26i72gK83kxyc
###  Users
POST {{baseUrl}}/users HTTP/1.1
content-type: application/json

{
    "name": "Wilson",
    "email": "wilson@sample.com",
    "password": "123456"
}
### Authenticate with password

POST {{baseUrl}}/sessions/password HTTP/1.1
content-type: application/json

{
    "email": "wilson@sample.com",
    "password": "261456"
}

### Get profile
GET {{baseUrl}}/profile HTTP/1.1
content-type: application/json
Authorization: Bearer {{ token }}

### Password recover
POST {{baseUrl}}/password/recover HTTP/1.1
content-type: application/json

{
    "email": "wilson@sample.com"
}

### Reset password
POST {{baseUrl}}/password/reset HTTP/1.1
content-type: application/json

{
    "code": "70f2a2b7-eb8c-46a2-ab58-b2c59271922d",
    "password": "261456"
}

